### ISSUE TITLE
{{badmatch,{normal,noproc}} intermitent in spawn_multiple_channels

### ISSUE THREAD

**Issue by sennui** [aeternity/aeternity#2994] opened 2019-11-06 16:56 UTC
## Actual Behavior
```
----------------------------------------------------
2019-11-06 12:24:13.144
miner_loop({miner,<0.14404.0>,false,80,[]})


%%% aesc_fsm_SUITE ==> all_tests.throughput.many_chs_msg_loop: FAILED
%%% aesc_fsm_SUITE ==> {{badmatch,{normal,noproc}},
 [{aesc_fsm_SUITE,receive_downs,3,
                  [{file,"/home/builder/aeternity/apps/aechannel/test/aesc_fsm_SUITE.erl"},
                   {line,1368}]},
  {aesc_fsm_SUITE,spawn_multiple_channels,5,
                  [{file,"/home/builder/aeternity/apps/aechannel/test/aesc_fsm_SUITE.erl"},
                   {line,1357}]},
  {test_server,ts_tc,3,[{file,"test_server.erl"},{line,1754}]},
  {test_server,run_test_case_eval1,6,[{file,"test_server.erl"},{line,1263}]},
  {test_server,run_test_case_eval,9,[{file,"test_server.erl"},{line,1195}]}]}
...............................................................................................................................................
%%% aesc_txs_SUITE: ....................................................................................................................................................................
%%% aecore_errorfree_SUITE: ..
%%% aecore_txs_SUITE: ....
%%% aehttp_discriminator_SUITE: ..
%%% aehttp_sc_SUITE: ........................................................................
%%% aehttp_spec_SUITE: .
%%% aemon_default_config_SUITE: .
%%% aebytecode_aevm_SUITE: .
%%% aevm_chain_SUITE: ...
%%% contract_solidity_bytecode_aevm_SUITE: ...
%%% contract_sophia_bytecode_aevm_SUITE: ...............
%%% name_resolution_SUITE: ....
%%% sophia_bytecode_aevm_SUITE: .
EXPERIMENTAL: Writing retry specification at /home/builder/aeternity/_build/test/logs/retry.spec
              call rebar3 ct with '--retry' to re-run failing cases.
Failed 1 tests. Passed 447 tests. 
Results written to "/home/builder/aeternity/_build/test/logs/index.html".
===> Failures occurred running tests: 1
Makefile:434: recipe for target 'internal-ct' failed
make[1]: *** [internal-ct] Error 1
make[1]: Leaving directory '/home/builder/aeternity'
Makefile:219: recipe for target 'ct-iris' failed
make: *** [ct-iris] Error 2
Exited with code 2
```

## Steps to Reproduce the Problem

  Intermitent in test_latest_otp21 job

**Comment by velzevur** [comment] 2019-11-08 10:07
This is a duplicate of #2945 which had been fixed by  #2960. Closing this issue

**Closed** 2019-11-08 10:07 UTC
Labels: area/statechannels, kind/bug
